# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae422b8687f057ac6f0578c2ec0cd68972274b55ce5cb624cee88e65fe50fbaa685b32d6d9060fe65900b4f828ac0c1f9fabd70e6ddb11b2f08a3311c1f5fcf0

test:
  secret_key_base: 4aa4d17bb08f746662d4ce49e324a88418288fd6233204e4054f39069ddcfe9ec99ae7c82f6fe8129182aaa1c03914f4200b173e7fe0c32e8a74e849271e4da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
